### ISSUE TITLE
URL #includes do not work

### ISSUE THREAD

**Issue by jeremy-rifkin** [Headline/discord-compiler-bot#129]
CE supports URL #includes but for some reason they do not work with compiler bot requests:

![image](https://user-images.githubusercontent.com/51220084/156421930-827ab226-7109-40b4-a4f6-af06e3d6ccc3.png)

**Comment by Headline** [comment]
Seems pretty reasonable for us to support this also. 

Compiler Explorer parses include statements and sends the http requests from the client browser, since we're hitting the API directly we don't have this feature. I imagine with some parsing/regex/magic we can implement this ourselves, thanks for opening this.

**Comment by jeremy-rifkin** [comment]
Thanks for investigating, I didn't actually realize that was possible from the client (thought that would be a cross-origin HTTP issue).

**Comment by jeremy-rifkin** [comment]
Thank you @Headline!
