### ISSUE TITLE
Output format: Get rid of the embed and use a code block

### ISSUE THREAD

**Issue by GalaxySH** [Headline/discord-compiler-bot#85]
Honestly, and I have heard a decent number of people share this opinion, but the output from code execution would look a lot better if it just used a standard code block. The one thing the embed has going for it is that it provides more color contrast. If the output were made into an embed, there would also be more room for multi-page output. The RichEmbed compresses the code in a small text area, and it isn't great for code viewing.

I hope this FR can be considered.

**Comment by Headline** [comment]
I agree with the spirit of this FR, but I'm not sure a single codeblock could contain all the relevant information in a way that's organized and easy to digest. I do agree that we can improve on how output is displayed (ref: #83), but I don't think formatting everything via text in a codeblock is the best way to do it. 

Our primary users are those who require very little output, large output was never a requirement for this software, but there's definitely ways that we can handle this better. What do you think of the idea that when a program's output is > discord's embed limit (2048 if I can recall correctly), we resort to uploading a file containing the output instead of truncating it?

**Comment by GalaxySH** [comment]
I can see that when not using the current output embed, some output information is lost, which is not great. It also lowers the max char count from 6000 to 2000.

Before thinking about output files, something to consider would be outputting the actual program result in the text content space above the embed.

Alternatively, to keep it all in the embed, you could consider pagination (using the convenient emoji system). The pages would cycle through the Program Output field.

Lastly, you could consider dumping the program output in a text file. I only put this last because it is probably the last resort option. It is the least convenient experience for discord users, but it is a safe way to handle overflow from the output. It isn't a very nice experience to have to download the text file and then preview it, especially for mobile users, if for some reason they are using the compiler like that. It is almost easier just to click on the Wandbox permalink.

**Comment by Headline** [comment]
> Alternatively, to keep it all in the embed, you could consider pagination (using the convenient emoji system). The pages would cycle through the Program Output field.

I've taken some time to consider all the options brought up in this issue and personally I feel that this solution is likely our best path going forwards, it's not really bringing anything new for the users to learn and should be intuitive to use.
